Fixed errors in identify_gene_isoform.py
1. Missing colon in function definition update_gene_dicts:
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
  File "bin/identify_gene_isoform.py", line 83
    def update_gene_dicts(chrom, j, gene, junctions, gene_unique_juncs, junc_to_gene)
                                                                                    ^
SyntaxError: invalid syntax
Filtering isoforms
Renaming isoforms



2. Function call that was not properly refactored in a previous commit:
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Traceback (most recent call last):
  File "bin/identify_gene_isoform.py", line 132, in <module>
    junc_to_tn, tn_to_juncs, all_se = update_dicts(chrom, junctions, prev_transcript, \
NameError: name 'update_dicts' is not defined
Filtering isoforms
Renaming isoforms