Fixed temp directory error in flair.py
Original code gave the following problem when specifying my own temp directory:
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Filtering isoforms
Renaming isoforms
Aligning reads to first-pass isoform reference
Traceback (most recent call last):
  File "flair.py", line 289, in <module>
    args.o+'.firstpass.fa', r], stdout=open(alignout+'.sam', "w")):
FileNotFoundError: [Errno 2] No such file or directory: '.../tmp//tmpp20_kgoo/.firstpass.sam'

Line 271 creates a file path, but the tempfile_name[] bit is surrounded by a '/' on both sides, turning it into a never created sub directory of the tmp file specified. I assumed the / is too much but perhaps you prefer to create the directory first instead.

Also, the generic except on line 297 caught the error without telling the actual problem it ran into, hence I included the original error message itself instead for debugging.